apiVersion: v1
kind: ConfigMap
metadata:
  name: dekoratoren-config
  namespace: personbruker
  annotations:
    reloader.stakater.com/match: "true"
data:
  ta-config.json: |
    {
      "test" : "great success!"
    }