apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app: nav-dekoratoren
    team: personbruker
  name: nav-dekoratoren-everyones-invited
  namespace: personbruker
spec:
  podSelector:
    matchLabels:
      app: nav-dekoratoren
  ingress:
  - {}
  policyTypes:
  - Ingress
