name: Deploy prod-gcp NetworkPolicy
on:
  push:
    branches:
      - master
    paths:
      - .nais/network-policy/network-policy-prod.yml

jobs:
  deploy_network_policy:
    name: Deploy prod-gcp NetworkPolicy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/network-policy/network-policy-prod.yml