name: Deploy dev-gcp NetworkPolicy
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .nais/network-policy/network-policy-dev.yaml

jobs:
  deploy_network_policy:
    name: Deploy dev-gcp NetworkPolicy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: .nais/network-policy/network-policy-dev.yaml